name: Build and publish image to Docker
on: 
    push:
        branches:
            - Main

jobs:
    publish_image:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: Build image
              run: docker build ./Docker/ -t haagensenk/whktest:latest
            - name: push image to docker
              run: |
                docker push haagensenk/whktest:latest